project:
  type: website
  output-dir: ../docs

website:
  title: "CSSS 2024"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - gallery.qmd
  
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - about.qmd
      - gallery.qmd
      
      - section: Projects
        auto: projects
          
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



