---
title: "About"
---


## Art in Complexity 
### A manifesto for visual collective experimentation  
 
If (complexity) science requires a hypothesis, art requires a portfolio. Here, we propose to combine both in an immersive and interactive way that brings complexity concepts into the public domain. While static representations of complex phenomena provide foundational understanding, they often fail to capture the emergent, dynamic, and aesthetically pleasing behavior inherent in these systems. This manifesto advocates for embracing the art within complexity, transforming abstract scientific concepts into accessible, playful, and visually appealing experiences. 

As a two-part project, we propose both the creation of a living digital archive and an exhibition to bring people closer to complexity. As part of the digital archive, we have compiled examples illustrating key scientific concepts in an engaging way:

#### Chaos Sampler
Chaotic systems, characterized by small changes leading to massive, unpredictable outcomes, are everywhere in nature. This interactive demo uses the Lorentz attractor to remix music recordings unpredictably, illustrating the creative potential of chaos.

#### Flocking behavior
An interactive simulation of flocking behavior demonstrating emergent phenomena.

#### Evolution
Fitness landscapes, essential in evolutionary biology, help visualize how populations respond to natural selection. Unlike static images, our simulations allow users to interact with parameters like population size and mutation rates, and experiment with dynamic "seascapes" to understand evolution in changing environments and explore the concept of "evolvability."

#### Game of Life
Conway’s Game of Life demonstrates how simple rules can generate complex behaviors on a 2-dimensional grid, where cells live or die based on their neighbors. This demo simulates the game, using sounds and a Novation Launchpad to create a unified physical, auditory, and visual experience, illustrating the emergence of complexity.

#### Physical emergence
An example of collective painting, how many parts can make a new whole.

#### Gallery
Beauty often naturally emerges in research on complexity. Created to compile images and media generated by participants of this summer school as a starting point, this gallery aims to continue incorporating everyone’s complexity inspirations encountered during our tinkering.

#### Goals
Designed to travel to multiple locations and reach a diverse audience, the exhibition we propose offers an interactive experience, allowing visitors to touch and move physical objects, thereby humanizing complexity. It highlights the aesthetic dimensions and emergent properties of complex systems through networks of interactions, educational modules, and artistic installations. Visitors will be able to immerse themselves in the simplicity of complexity, exploring everything from biological microscopic systems to macroscopic classical physics. The exhibition's design will enable participants to act both as spectators and integral parts of the system, illustrating the concept that the whole is greater than the sum of its parts and that, as with complex systems, interactive art also defies complete predictability.
 
As accompanying material for the exhibition, the development of educational modules is suggested, using platforms such as Complexity Explorer, to disseminate the concepts presented in the exhibition. These modules will teach participants to transform their favorite complexity concepts into art objects, either physical or digital.
 
In essence, both the living digital archive and the exhibition aim to be a dynamic and visual collective exploration of complex systems, showing that science and art are not mutually exclusive but rather complementary ways through which we can appreciate the world.
